GET  http://localhost:5000 HTTP/1.1
content-type: application/json

###

POST  http://localhost:5000/login HTTP/1.1
content-type: application/json

{
    "Email": "oaktan@gmail.com",
    "Pasword":"1234"
}

###

POST http://localhost:5000/user HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQZXJzb25JRCI6MSwiaWF0IjoxNjEwNzUwNTg5LCJleHAiOjE2MTEzNTUzODl9.7yC-Be1d_Oo4fWdPMFKfilqPW8NrqhnDgDAUggvSp3U
content-type: application/json

{
    "Name":"apicalldeneme",
    "Surname":"apicalldeneme",
    "Email": "apicalldeneme@gmail.com",
    "UserName":"apicalldeneme", 
    "Pasword": "apicalldeneme123"
}

###

GET http://localhost:5000/user HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQZXJzb25JRCI6MSwiaWF0IjoxNjEwNzUwNTg5LCJleHAiOjE2MTEzNTUzODl9.7yC-Be1d_Oo4fWdPMFKfilqPW8NrqhnDgDAUggvSp3U
content-type: application/json

{
    "UserName":"oguz", 
    "Pasword": "1234"
}

###

GET http://localhost:5000/user/movies HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQZXJzb25JRCI6MSwiaWF0IjoxNjEwNzUwNTg5LCJleHAiOjE2MTEzNTUzODl9.7yC-Be1d_Oo4fWdPMFKfilqPW8NrqhnDgDAUggvSp3U
content-type: application/json

{
    "personId":10
}

###

POST  http://localhost:5000/user/movies HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQZXJzb25JRCI6MSwiaWF0IjoxNjEwNzUwNTg5LCJleHAiOjE2MTEzNTUzODl9.7yC-Be1d_Oo4fWdPMFKfilqPW8NrqhnDgDAUggvSp3U
content-type: application/json

{
    "personId":25,
    "tmdbid":37165,
    "title": "The Truman Show",
    "director":"Peter Weir",
    "relasedate": "2000-02-02", 
    "story": 1,
    "acting": 1,
    "editing": 1,
    "music": 2,
    "datewatch": "2000-02-03",
    "review": "apicalldeneme123"
}

###

POST http://localhost:5000/user/delete HTTP/1.1 HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQZXJzb25JRCI6MSwiaWF0IjoxNjEwNzUwNTg5LCJleHAiOjE2MTEzNTUzODl9.7yC-Be1d_Oo4fWdPMFKfilqPW8NrqhnDgDAUggvSp3U
content-type: application/json

{
    "UserName":"cetiner"   ,
    "Email": "cetiner@gmail.com"
}

###

POST http://localhost:5000/user/update HTTP/1.1 HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQZXJzb25JRCI6MSwiaWF0IjoxNjEwNzUwNTg5LCJleHAiOjE2MTEzNTUzODl9.7yC-Be1d_Oo4fWdPMFKfilqPW8NrqhnDgDAUggvSp3U
content-type: application/json

{
    "personId" : "11",
    "Email": "arslan123@gmail.com"
}

###

GET http://localhost:5000/user/all/users HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQZXJzb25JRCI6MSwiaWF0IjoxNjEwNzUwNTg5LCJleHAiOjE2MTEzNTUzODl9.7yC-Be1d_Oo4fWdPMFKfilqPW8NrqhnDgDAUggvSp3U
content-type: application/json