GET  http://localhost:5000 HTTP/1.1
content-type: application/json

###

POST  http://localhost:5000/login HTTP/1.1
content-type: application/json

{
    "Email": "Firsttry-email",
    "Pasword":"firsttry"
}

###

POST http://localhost:5000/user HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDExMzU0NDQsImV4cCI6MTY0MjM0NTA0NH0.ZK2gSvYvQNzhoDlTFR-E35U1XVqxDpJxGkq1gv6ddlg
content-type: application/json

{
    "UserName":"apicalldeneme",
    "Filmname":"apicalldeneme",
    "LastName":"apicalldeneme",
    "Email": "apicalldeneme@gmail.com",
    "Password": "apicalldeneme123",
    "AvatarUrl":"exampleurl.com"
}

###

GET http://localhost:5000/user HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDExMzU0NDQsImV4cCI6MTY0MjM0NTA0NH0.ZK2gSvYvQNzhoDlTFR-E35U1XVqxDpJxGkq1gv6ddlg
content-type: application/json

{
    "UserName":"Firsttry", 
    "Pasword": "firsttry"
}
###

DELETE http://localhost:5000/user HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDExMzU0NDQsImV4cCI6MTY0MjM0NTA0NH0.ZK2gSvYvQNzhoDlTFR-E35U1XVqxDpJxGkq1gv6ddlg
content-type: application/json

{
    "UserName":"apicalldeneme", 
    "Email": "apicalldeneme@gmail.com"
}

###

PUT http://localhost:5000/user HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDExMzU0NDQsImV4cCI6MTY0MjM0NTA0NH0.ZK2gSvYvQNzhoDlTFR-E35U1XVqxDpJxGkq1gv6ddlg
content-type: application/json

{
    "Id": 3 ,
    "UserName":"apicalupdate",
    "Filmname":"apicalldeneme",
    "LastName":"apicalupdate",
    "Email": "apicalldeneme@gmail.com",
    "Password": "apicalldeneme123",
    "AvatarUrl":"exampleurl.com"
}

###

GET http://localhost:5000/user/movies HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDExMzU0NDQsImV4cCI6MTY0MjM0NTA0NH0.ZK2gSvYvQNzhoDlTFR-E35U1XVqxDpJxGkq1gv6ddlg
content-type: application/json

{
    "PersonID":10
}

###

POST  http://localhost:5000/user/movies HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDExMzU0NDQsImV4cCI6MTY0MjM0NTA0NH0.ZK2gSvYvQNzhoDlTFR-E35U1XVqxDpJxGkq1gv6ddlg
content-type: application/json

{
    "PersonID":25,
    "tmdbid":37165,
    "title": "The Truman Show",
    "director":"-",
    "relasedate": "2000-02-02", 
    "story": 1,
    "acting": 1,
    "editing": 1,
    "music": 2,
    "datewatch": "2000-02-03",
    "review": "apicalldeneme123"
}

###

GET http://localhost:5000/user/series HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDExMzU0NDQsImV4cCI6MTY0MjM0NTA0NH0.ZK2gSvYvQNzhoDlTFR-E35U1XVqxDpJxGkq1gv6ddlg
content-type: application/json

{
    "PersonID":10
}

###

POST  http://localhost:5000/user/series HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDExMzU0NDQsImV4cCI6MTY0MjM0NTA0NH0.ZK2gSvYvQNzhoDlTFR-E35U1XVqxDpJxGkq1gv6ddlg
content-type: application/json

{
    "PersonID":10,
    "tmdbid":37165,
    "title": "The Truman Show",
    "producer":"",
    "relasedate": "2000-02-02", 
    "story": 1,
    "acting": 1,
    "editing": 1,
    "music": 2,
    "datewatch": "2000-02-03",
    "review": "apicalldeneme123"
}

###

POST http://localhost:5000/user/delete HTTP/1.1 HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDExMzU0NDQsImV4cCI6MTY0MjM0NTA0NH0.ZK2gSvYvQNzhoDlTFR-E35U1XVqxDpJxGkq1gv6ddlg
content-type: application/json

{
    "UserName":"cetiner"   ,
    "Email": "cetiner@gmail.com"
}

###

POST http://localhost:5000/user/update HTTP/1.1 HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDExMzU0NDQsImV4cCI6MTY0MjM0NTA0NH0.ZK2gSvYvQNzhoDlTFR-E35U1XVqxDpJxGkq1gv6ddlg
content-type: application/json

{
    "PersonID" : "11",
    "Email": "arslan123@gmail.com"
}

###

GET http://localhost:5000/user/all/users HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDExMzU0NDQsImV4cCI6MTY0MjM0NTA0NH0.ZK2gSvYvQNzhoDlTFR-E35U1XVqxDpJxGkq1gv6ddlg
content-type: application/json